### ISSUE TITLE
Remove template parameters from compute_number_of_hash_functions and set_up_parameters

### ISSUE THREAD

**Issue by ludwigschmidt** [FALCONN-LIB/FALCONN#15]
They are not really needed in these interface functions.

We might want a field in LSHConstructionParameters instead.

**Comment by ludwigschmidt** [comment]
Probably also rename set_up_parameters to set_default_parameters to make clear it sets defaults and is not necessary to initialize a LSHConstructionParameters struct.

**Comment by ludwigschmidt** [comment]
I renamed `set_up_parameters` to `get_default_parameters` (get instead of set because we don't pass a LSHConstructionParameters struct as an argument).

I decided to keep the template parameter for the helper functions for consistency with the construct_table function for now.

Wiki updated accordingly, doxygen docs should be re-generated.

**Comment by ilyaraz** [comment]
Done with doxygen.
