### ISSUE TITLE
Make a list of contributors

### ISSUE THREAD

**Issue by ludwigschmidt** [FALCONN-LIB/FALCONN#16]
We should keep track of people who report bugs, help with testing, etc.!

So far we have:
- Grey Ballard
- Dhiraj Holden
- Ilya Kornakov
- Andrew Sabisch

**Comment by ilyaraz** [comment]
And, whoever ran FALCONN on their machines: Dhiraj Holden, Andrew Sabisch and Ilya Kornakov.

**Comment by ilyaraz** [comment]
Added: 512890d14478f3d94ecf0db1af235ce9497e4f23
