### ISSUE TITLE
Rename find_closest ?

### ISSUE THREAD

**Issue by ludwigschmidt** [FALCONN-LIB/FALCONN#17]
We have the following methods for getting near(est) neighbors:
- `find_closest`
- `find_k_nearest_neighbors`
- `find_near_neighbors`

I find this a little inconsistent. Should we rename `find_closest` to `find_nearest_neighbor`?

**Comment by ilyaraz** [comment]
Agree on this one.

**Comment by ludwigschmidt** [comment]
Code changed in df58da4cc650063d0bbb5f3f1981f24712a1af4a , wiki and doxygen still need updating.

**Comment by ludwigschmidt** [comment]
I also updated the wiki. Only doxygen left.

**Comment by ilyaraz** [comment]
Done with doxygen.
