### ISSUE TITLE
random_benchmark is slow under Cygwin when num_setup_threads > 1

### ISSUE THREAD

**Issue by ilyaraz** [FALCONN-LIB/FALCONN#41]

**Comment by ludwigschmidt** [comment]
Is this a bug in Cygwin's pthreads?

**Comment by ilyaraz** [comment]
So, the issue seems to be that Eigen's `middleRows`, which is used for the Hyperplane LSH, from the same matrix does not work well when used in several threads.

Since Eigen does not support Cygwin well, we decided not to introduce yet another ugly workaround for this issue for now. If you really need to use FALCONN under Cygwin, set the number of threads to 1.

One clean workaround would be to parallelize the table set-up procedure with respect to points (as opposed to tables). It will fix this issue as a by-product.
