### ISSUE TITLE
Compilation errors because of SWIG

### ISSUE THREAD

**Issue by ilyaraz** [FALCONN-LIB/FALCONN#48]
http://pastebin.com/H47sFCKv

**Comment by ilyaraz** [comment]
Seems to be isomorphic to https://github.com/Rostlab/relna/issues/10

**Comment by ludwigschmidt** [comment]
I had a quick look, could this be Python 3 related? And if I understand this issue correctly, there is a fix for it (see the conversation in #14).

@wbittremieux , could you share your solution? Thank you!

**Comment by bittremieux** [comment]
@ludwigschmidt The problem for me was that on line 16 in the makefile `NUMPY_INCLUDE_DIR` is hard-coded to NumPy installed for Python 2.7, which caused these errors when I tried to install under Python 3.5.

After changing that line (and changing `swig3.0` to `swig` on the preceding line as per #14) I could install without any problems.

**Comment by ludwigschmidt** [comment]
Thanks! That's good to know. We should really get a more robust makefile for FALCONN.

**Comment by ilyaraz** [comment]
Ah, OK, I silently assumed this was a result of `pip install falconn`.
