### ISSUE TITLE
Release v1.3

### ISSUE THREAD

**Issue by ilyaraz** [FALCONN-LIB/FALCONN#50]
- [ ] Expose linear scan
- [ ] Make the inner tables return the amount of memory they use
- [ ] Parameter search in the wrapper
- [ ] Add query objects to wrapper for multi-threaded querying (#6)
- [ ] Add check in wrapper for k and bit-packed table (#45)

**Comment by ludwigschmidt** [comment]
Might be good to take care of a few clean-up issues like #32 and #14 also.
