### ISSUE TITLE
Do we have the multi-thread safe version LSHTable?

### ISSUE THREAD

**Issue by sbihero** [FALCONN-LIB/FALCONN#55]
I tried to use find_k_nearest_neighbors function in multi-thread, but got the "double free or corruption" error.
So do we have the multi-thread safe version of LSHTable?

**Comment by ludwigschmidt** [comment]
Thanks for your feature request! We have planned a thread-safe query interface for v1.3 of FALCONN, and it's good to know that people are interested in the feature :-)

We should have v1.3 ready by the end of May. If you urgently need thread support before then, please send an email to falconn.lib@gmail.com so we can get in touch and talk about options (the core query classes of FALCONN are already thread-safe, we mainly need to expose the thread-safe functionality in the wrapper(s)).

**Comment by ludwigschmidt** [comment]
I'll close this issue because it is the same as #6 .
