### ISSUE TITLE
Provide a thread-safe version of the LSH table

### ISSUE THREAD

**Issue by ludwigschmidt** [FALCONN-LIB/FALCONN#6]

**Comment by erikbern** [comment]
Take a look here: https://github.com/erikbern/ann-benchmarks/pull/28

I'm re-running ann-benchmarks with multiple threads so that we can max out the CPU cores. I think it's a bit more fair as a benchmark since some libraries may use BLAS/Eigen which are multithreaded under the hood.

The results for FALCONN are quite bad so it would be great if there's an easy way for you to support multithreading.

**Comment by ilyaraz** [comment]
I wonder how you managed to make the FALCONN's results _worse_ than they were before... I will be able to get back to this no earlier than September though.

**Comment by erikbern** [comment]
Yeah it's really weird. I'm guessing there's a lack of thread safety here and for some reason doing multiple queries simultaneously breaks the data structures? Is FALCONN mutable on queries?

**Comment by erikbern** [comment]
Until the fix, I'll set the number of threads for the FALCONN benchmarks to 1. That way the results won't use the full parallelism of the machine, but at least the threading issue won't cause these bad results

**Comment by ludwigschmidt** [comment]
Yup, FALCONN is mutable on queries. Basically each query object keeps an array of size num_points for de-duplicating the results from the LSH tables efficiently. If multiple threads use the same query object, they might probably interfere badly in this stage.

The core classes are written with threading in mind, we just haven't had time to expose them in a thread-safe way yet.

**Comment by erikbern** [comment]
I think FALCONN uses threaded BLAS under the hood, so it's still getting some performance improvement from threading. So it might not be a big deal.

What do you mean with query object? Can you create a separate query object for each thread?

**Comment by ludwigschmidt** [comment]
I'm not sure if FALCONN benefits from multiple threads. We use Eigen for linear algebra and as far as I know it doesn't multi-thread the operations we use (mostly vector-vector inner products). Did you see a performance improvement?

The query object in https://github.com/FALCONN-LIB/FALCONN/blob/master/src/include/falconn/core/nn_query.h is thread safe (but unfortunately not exposed to Python at the moment).

Both Ilya and I are doing summer internships at the moment, so we don't have as much time for FALCONN as we'd like. We'll release a multi-threaded version when we're back at MIT in September.

**Comment by ludwigschmidt** [comment]
Note for @ilyaraz : we might need to call swig with "-threading" or something similar to get a GIL-free python wrapper.

**Comment by ilyaraz** [comment]
Done in v1.3.1.
