### ISSUE TITLE
pip install FALCONN failed on windows 7

### ISSUE THREAD

**Issue by zctzzy** [FALCONN-LIB/FALCONN#62]
I use Anaconda2 64 bit on my Windows 7 system. After I typed "pip install FALCONN", it downloads the FALCONN package and attempt to install but I got the following errors:

 KeyType = int; PointSet = falconn::PlainArrayPointSet<float>]'
    falconn/swig/python_wrapper.h:337:31:   required from here
    falconn/src/include/falconn/wrapper/../core/polytope_hash.h:90:9: error: 'posix_memalign' was not declared in this scope
    In file included from falconn/external/eigen/Eigen/Core:344:0,
                     from falconn/external/eigen/Eigen/Dense:1,
                     from falconn/src/include/falconn/eigen_wrapper.h:11,
                     from falconn/src/include/falconn/falconn_global.h:8,
                     from falconn/swig/falconn_wrap.cc:3689:
    falconn/external/eigen/Eigen/src/Core/arch/SSE/PacketMath.h: In function 'Packet Eigen::internal::pmadd(const Packet&, const Packet&, const Packet
&) [with Packet = __vector(2) double]':
    falconn/external/eigen/Eigen/src/Core/arch/SSE/PacketMath.h:250:134: warning: control reaches end of non-void function [-Wreturn-type]
    falconn/external/eigen/Eigen/src/Core/arch/SSE/PacketMath.h: In function 'Packet Eigen::internal::pmadd(const Packet&, const Packet&, const Packet
&) [with Packet = __vector(4) float]':
    falconn/external/eigen/Eigen/src/Core/arch/SSE/PacketMath.h:249:134: warning: control reaches end of non-void function [-Wreturn-type]
    error: command 'C:\Anaconda2\MinGW\bin\gcc.exe' failed with exit status 1

```
----------------------------------------
```

Command "C:\Anaconda2\python.exe -u -c "import setuptools, tokenize;**file**='c:\users\admini~1\appdata\local\temp\pip-build-xmpbnu\FALCONN\se
tup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record c:\users\admini~1\ap
pdata\local\temp\pip-yj92v2-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\admini~1\app
data\local\temp\pip-build-xmpbnu\FALCONN\

**Comment by ludwigschmidt** [comment]
I'm not familiar with the Anaconda build environment on Windows. What compiler does it use? The error is about a missing `posix_memalign`, which indicates that it's not a POSIX-compatible build environment.

**Comment by ilyaraz** [comment]
In general, we do not support Windows. In principle, FALCONN can be run under Cygwin, but the performance will be sub-optimal due to #30. Consider installing Ubuntu in a virtual machine.

Your error is due to the fact that MinGW does not support `posix_memalign`. There seems to be a workaround: http://stackoverflow.com/questions/10862121/undefined-reference-to-posix-memalign-using-mingw32 , but for this you need to clone the repository, replace all calls of `posix_memalign` with `_aligned_malloc`, and then install the Python package by running `make python_package_install`.

**Comment by zctzzy** [comment]
OK. Got it. I will test it on Ubuntu OS. Thank you @ludwigschmidt @ilyaraz

**Comment by zctzzy** [comment]
OK, I got it. I will test it on virtual machine with Ubuntu OS. Thank you.

chuanting.zhang@gmail.com

From: Ilya Razenshteyn
Date: 2016-10-23 11:07
To: FALCONN-LIB/FALCONN
CC: Chuanting Zhang; Author
Subject: Re: [FALCONN-LIB/FALCONN] pip install FALCONN failed on windows 7 (#62)
In general, we do not support Windows. FALCONN can be run under Cygwin, but the performance is sub-optimal due to #30. Consider installing Ubuntu in a virtual machine.
Your error is due to the fact that MinGW does not support posix_memalign. There seems to be a workaround: http://stackoverflow.com/questions/10862121/undefined-reference-to-posix-memalign-using-mingw32 , but for this you need to clone the repository, replace all calls of posix_memalign with _aligned_malloc, and then install the Python package by running make python_package_install.

**Comment by ilyaraz** [comment]
FWIW, on the recent Cygwin version of gcc, `posix_memalign` is not supported as well.

**Comment by ludwigschmidt** [comment]
How does it not work as well? Does it return only half the bytes you ask for? :-)
