### ISSUE TITLE
Migrate Python wrapper to pybind11

### ISSUE THREAD

**Issue by ludwigschmidt** [FALCONN-LIB/FALCONN#69]
pybind11 is a fairly new project for accessing C++ code from Python:

https://github.com/pybind/pybind11

There are three advantages for us:

- They translate from Scipy sparse matrices to Eigen sparse matrices. This would make #24 easy to implement.
- It's a header-only library, so we can add it to 'external'.
- The project is actively developed and has very good documentation. It's specifically for connecting C++ and Python, so the semantics are often clearer than in the more generic swig.

pybind11 is planning to release v2 in early January. v2 brings many improvements for the Eigen wrapper, so it's probably good to start with v2 on our side.

**Comment by ilyaraz** [comment]
Done in v1.3.1.

**Comment by ajaykmr2292** [comment]
I would like to know how to use sparse matrices in python for FALCONN?
