### ISSUE TITLE
Compilation error on Visual Studio 2015, X64

### ISSUE THREAD

**Issue by cliassh** [FALCONN-LIB/FALCONN#71]
It shows:"C3861	'__builtin_prefetch': identifier not found	FastLSH	d:\setup\falconn-1.2.2\src\include\falconn\core\prefetchers.h	57"

Anyone can help?

**Comment by ludwigschmidt** [comment]
Unfortunately we do not support Visual Studio at the moment. However, the prefetching instructions are only there to get a moderate performance improvement. If you simply comment out the `__builtin_prefetch` (so that the prefetcher does nothing), FALCONN should still work correctly.

**Comment by cliassh** [comment]
Thank you for quick reply, My bad I didn't look carefully at the Wiki home page.

After commenting out __builtin_prefetch , there are still a lot of errors, so I decided to turn to flann library.
