### ISSUE TITLE
How to find near neighbors in given candidates instead of all candidates

### ISSUE THREAD

**Issue by qolina** [FALCONN-LIB/FALCONN#72]
Hi,

I know the definition of find_near_neighbors are as follows:
```
def find_near_neighbors(self, query, threshold)
Find all the points within threshold distance from query.
```

I would like to know how to calculate near neighbors within distance of threshold from a GIVEN candidates. For example, given smaller candidates is provided as a list of indexes.

Actually, I have a large dataset, I only want to calculate a document's nearest neighbors in a time window [-3 days, +3 days]. And I want to avoid to build a LSH index for each days' data.

Thanks very much.

**Comment by ludwigschmidt** [comment]
First a little background. `find_near_neighbors` works in two steps:

1. Generate a set of candidates for the given `query`.
2. Compute distances for the candidates and return only those with distance less than `threshold`.

FALCONN doesn't directly support the operation you are asking for, but you can do the following:

1. Generate a set of candidates for the given query with FALCONN's `get_unique_candidates`.
2. Compute the set intersection of the returned index set with your smaller candidate set (+/- 3 days).
3. Compute the actual distances for the remaining indices in the intersection.

For high-accuracy queries, most of the time is spent in the distance computation (not in the candidate generation). So the approach above should be fairly efficient.

Let me know if you have any questions.

**Comment by qolina** [comment]
Thanks. Still have some problems dealing with time-cost. I can figure out how to do first two steps. About step 3, do you mean use other distance calculate method instead of LSH's? What a pity, time cost becomes larger than previous LSH `find_near_neighbors`. Already tried sklearn, scipy's several distance calculations.  Do LSH provide quick distance calculation?

**Comment by ludwigschmidt** [comment]
FALCONN uses LSH only to generate a set of candidate points. Once we have the candidate points, we compute the distances with standard linear algebra routines.

Which distance function are you interested in? Doing the distance computation in Python should be just as fast with numpy.

**Comment by qolina** [comment]
I use cosine, as it fits better for texts.
Don't know why it's much slower than LSH.. Already tried scipy..

**Comment by qolina** [comment]
Thanks anyway.

**Comment by ludwigschmidt** [comment]
Interesting that our distance computation is much faster than scipy's. You can have a look at how we compute cosine nearest neighbors in Python here:

https://github.com/FALCONN-LIB/FALCONN/blob/master/src/python/benchmark/random_benchmark.py#L118
