### ISSUE TITLE
How can I insert more elements into the hash table

### ISSUE THREAD

**Issue by mpkuse** [FALCONN-LIB/FALCONN#78]
I have an initial data loaded into the hash table with ```.setup()``` call. How can I insert more elements 
into the hash table?

**Comment by willard-yuan** [comment]
As far as I know, FALCONN doesn't support inserting or removing some record dynamically. You can see this issue #2 for more discussion.

**Comment by ludwigschmidt** [comment]
Thanks for helping out, @willard-yuan ! Your answer is correct.
