### ISSUE TITLE
How to serialize the hash_table object?

### ISSUE THREAD

**Issue by yangxian10** [FALCONN-LIB/FALCONN#79]
Though FALCONN is wonderful, it has not provided model serialize function, and I find it is not easy to implement it.

**Comment by ludwigschmidt** [comment]
The feature request for this is in issue #46 . Hopefully we'll get to it this summer. At some point @dpankrat mentioned that he was working on adding serialization to FALCONN. I'm not sure what happened to this effort.

**Comment by frankie-yanfeng** [comment]
@ludwigschmidt 
Hello, 
May I know the current progress on the hash_table object serialization as per now? Thanks.

**Comment by ludwigschmidt** [comment]
Unfortunately we haven't had time yet to work on this. If someone is interested in implementing the serialization functionality, we'd be happy to add it to FALCONN.
