### ISSUE TITLE
No url found for submodule path 'external/pybind11/tools/clang'

### ISSUE THREAD

**Issue by miguelmezamartinez** [FALCONN-LIB/FALCONN#81]
Hi

I had been making some experiments with your library for the last couple of months. I was able to include your library in my project as an external element in my Cmakelist. I'm relative new to all of this and was able to make it work by following some other project that was provided to me. Everything was working perfectly until a few days ago. I don't know if it was caused by some of the modifications to the project but I'm quite lost on where to start looking at. I decided to give it a try and post this issue to see if you would have any suggestions. This is the error I'm getting

fatal: No url found for submodule path 'external/pybind11/tools/clang' in .gitmodules
CMake Error at /home/mike/git/google_ngram_analysis/cpp/build/eigen/tmp/project_eigen-gitclone.cmake:84 (message):
  Failed to init submodules in:
  '/home/mike/git/google_ngram_analysis/cpp/build/eigen/src/project_eigen'
make[2]: *** [CMakeFiles/project_eigen.dir/build.make:91: eigen/src/project_eigen-stamp/project_eigen-download] Error 1
make[1]: *** [CMakeFiles/Makefile2:875: CMakeFiles/project_eigen.dir/all] Error 2

Thx a lot for any help you could provide

**Comment by ilyaraz** [comment]
We have recently added pybind11 as an external dependency, which is now yet another submodule. I suspect it could be the problem?

**Comment by miguelmezamartinez** [comment]
?Thanks a lot for your reply. I will try to figure out how to integrate this new submodule.

In the meanwhile I figure out a way to point to a previous submit to continue with some experiments.



________________________________
