### ISSUE TITLE
fail to import falconn

### ISSUE THREAD

**Issue by kli017** [FALCONN-LIB/FALCONN#82]
get an  ImportError: /home/kli017/anaconda2/lib/python2.7/site-packages/_falconn.so: undefined symbol: _ZNSt28__atomic_futex_unsigned_base19_M_futex_wait_untilEPjjbNSt6chrono8durationIlSt5ratioILl1ELl1EEEENS2_IlS3_ILl1ELl1000000000EEEE

**Comment by ilyaraz** [comment]
What did you do to get this error? Did you just `pip install falconn`?

**Comment by kli017** [comment]
No, I have done the installation. After that i import falconn in python and got this error

**Comment by ilyaraz** [comment]
By `make python_package_install`?

**Comment by kli017** [comment]
No, by the pip install falconn and the result shows it was successfully installed.  I don't know if is it because I am using anaconda, since I saw other people got similar error when they import other library in anaconda.

**Comment by ilyaraz** [comment]
See here: https://github.com/FALCONN-LIB/FALCONN/issues/83

**Comment by kli017** [comment]
Thanks for the help, I uninstalled falconn 1.22 by pip and reinstall it by make python_package_install. It showed" Finished processing dependencies for FALCONN==2.0.0 ". However, when I import it in python I got a new import error...ImportError: /home/kli017/.cache/Python-Eggs/FALCONN-2.0.0-py2.7-linux-x86_64.egg-tmp/_falconn.so: undefined symbol: _ZNSt13runtime_errorC1EPKc

**Comment by kli017** [comment]
I didn't get swig in my environment. Should I install it first?

**Comment by ilyaraz** [comment]
You don't need SWIG for the new wrapper.

Weird. Which C++ compiler (and what version) do you have?

**Comment by kli017** [comment]
Yeah. I think it should be gcc 5.4.0 20160609(Ubuntu 5.4.0-6ubuntu1~16.04.4)

**Comment by ilyaraz** [comment]
Yes, it's likely to be due to Anaconda: https://github.com/NervanaSystems/aeon/issues/39 . Do you mind trying to use vanilla Python?

**Comment by kli017** [comment]
Ah I see, Thank you for the help, I will try it out later :+1:
