### ISSUE TITLE
Missing functionalities in python

### ISSUE THREAD

**Issue by kavehhassani** [FALCONN-LIB/FALCONN#83]
Hello,
I tried the run your glove example after pip installing falconn. However, some of the properties are missing from python package which results in error:

1.  module 'falconn' has no attribute 'LSHFamily'
2. module 'falconn' has no attribute 'DistanceFunction'
3. module 'falconn' has no attribute 'StorageHashTable'
4. 'LSHConstructionParameters' object has no attribute 'compute_number_of_hash_functions'

Any suggestions?

**Comment by ilyaraz** [comment]
We did upgrade the Python wrapper, but have not uploaded a newer version to pypi yet. Try to clone the repo, and run `make python_package_install` (within a virtual environment, if you are using `virtualenv`).

**Comment by kavehhassani** [comment]
Thanks, I did. Now I get a new error when importing it:

`~/code/FALCONN/python_package/dist/FALCONN-2.0.0/falconn/__init__.py in <module>()
     71 import numpy as _numpy
     72 import _falconn as _internal
---> 73 from _falconn import LSHConstructionParameters, QueryStatistics, DistanceFunction, LSHFamily, StorageHashTable, get_default_parameters, compute_number_of_hash_functions
     74
     75 class Queriable:

ImportError: cannot import name 'DistanceFunction'`

**Comment by kavehhassani** [comment]
Thank you it works perfect now.

**Comment by ilyaraz** [comment]
Great to hear!
