### ISSUE TITLE
some problems with python examples grove.py

### ISSUE THREAD

**Issue by beimingmaster** [FALCONN-LIB/FALCONN#93]
some code in grove.py:

```
# Perform linear scan using NumPy to get answers to the queries.
      print('Solving queries using linear scan')
      t1 = timeit.default_timer()
      answers = []
      for query in queries:
         answers.append(np.dot(dataset, query).argmax())
      t2 = timeit.default_timer()
      print('Done')
      print('Linear scan time: {} per query'.format((t2 - t1) / float(
          len(queries))))
```

in above code, what's the answer? the real answer is the nearest point according with query.
following code used distance is "EuclideanSquared", why the result of "np.dot(dataset, query).argmax()"  is the anwser?
is the formula of euclidean distance ||v1 - v2||?

**Comment by ilyaraz** [comment]
For this example, we assume that everything lies on the sphere. The formula is correct.
